### ISSUE TITLE
ENH: Tax Reform Explorer should be called "Tax Reform Visualization 1"

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/plots#10]
We will use a numbering scheme to keep track of the visualizations. They will likely have some meta data with a more descriptive name or short phrase that can explain the purpose of the viz, but in terms of the layout of directories, files, etc., the names should be "Tax Reform Visualization 1" and increment up from there as new viz assets are added.

**Comment by brendancol** [comment]
https://github.com/open-source-economics/taxplots/pull/6/commits/e5c2c83e27bb587851436b227fdac98ed5af1bf7

**Comment by brendancol** [comment]
@talumbau In the commit above, I change the name and info file accordingly
