### ISSUE TITLE
How to edit the fine print at bottom of plot? 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/plots#11]
Is editing [this line](https://github.com/open-source-economics/taxplots/blob/master/contrib/tax_reform_explorer/template.j2#L194) in `template.j2`the best way to replace the latin filler text at the bottom of TRV1? 

The text I'd like to add is:

---

_Explore the impact of eliminating itemized deductions on the simplicity of the tax system, the distribution of taxes across different income groups, and the potential for rate reduction._
**Credits:**
_Concept_: Alex Brill and Matt Jensen
_Development_: Brendan Collins and Sean Wang [T.J.?]
_Key open source projects_: [Tax-Calculator](www.github.com/open-source-economics/tax-calculator) and [TaxData](www.github.com/open-source-economics/tax-ca;ci;atpr) for tax computations. [Bokeh](bokeh.pydata.org) for visualizations. 
    _Hosting_: Open Source Policy Center at the American Enterprise Institute
**Version**: ###. Check for updates

---

Followup question: 

I'd very much appreciate feedback on this text and formatting given that it might become a standard

Should the hosting and versioning information be added later, perhaps when the viz is prepared for the ospc.org gallery rather than while it is still in OSE/plots?

**Comment by brendancol** [comment]
@MattHJensen at the moment, you would actually edit that `template.j2` and then run the `build-plots` command.  This is for text which actually part of the plot itself.  Maybe would could also consider adding attribution information to the `info.yml` file to be included in the gallery.

**Comment by MattHJensen** [comment]
Closed by #15.
