### ISSUE TITLE
TRV 1 text

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/plots#24]
— Top left:
- [x] fix spelling of "Mortgage”

— Top right:
- [x]  add "Deduction" after "Charitable Contribution”

— Chart on left:
- [x] capitalize "itemizing" in title, and capitalize "baseline" and "reform" in legend

— Text on left when all three deductions are kept:
- [x] Replace all three instances of "Implement a reform" with an ellipsis to more clearly tie each to "Repeal deductions above...”
- [ ] Hyphenate "revenue neutralizing”

— Text on left when any deduction is repealed:
- [ ] Move period after end parenthesis
- [x] Change “percent” to “%"

**Comment by brendancol** [comment]
this is an older issue which I believe has been addressed.  Closing up can reopen if needed.
