### ISSUE TITLE
METR plot, portrait issues

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/plots#33]
- [ ] Drop the negative space before 0.0%.
- [x] Double lining the long industry names (problematic)_
- [ ] Move the slider bar and label under the title and subtitle
- [ ] Wrap the title and subtitle as needed.
- [ ] Reduce the distance between tick marks.
- [ ] Find new slider widget that's better for mobile
- [ ] Drop right-side yaxis on portrait mode viz
- [ ] Notify everyone on the flow that those changes are available at the portrait URL for the viz

**Comment by brendancol** [comment]
@Jason, I don't think line-breaks in in axis labels will be possible

**Comment by brendancol** [comment]
@Jason, I think we've reach a good spot with the `corp_mettr` plot, I'm closing this for now but can reopen if needed.
