### ISSUE TITLE
ENH: Three additional values should be displayed in the viz

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/plots#7]
These values should appear in the visualization (with appropriate labels). They should probable be somewhere below the two main graphs:

total reduction in # itemizers

total revenue raised

revenue rate cut across the board that would be paid for by the chosen reform.

@GoFroggyRun will do the calculations. @brendancol will do the layout.

**Comment by GoFroggyRun** [comment]
The code I just updated [here](https://github.com/GoFroggyRun/Notebook/blob/master/TAXdata.ipynb) shall hopefully do the work. 
@MattHJensen, Could you review?

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun! I'll send a few comments.

**Comment by GoFroggyRun** [comment]
@MattHJensen I have added a few examples to the [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/TAXdata.ipynb). 
Could you review? Are there any reforms in particular you want me to check?

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun.

> Are there any reforms in particular you want me to check?

 I think it would make sense to use all of the permutations that are available with the widget. See http://ospc-taxes7.herokuapp.com/widgets/embed/tax_reform_explorer/. Note that real estate taxes are included with state and local.

**Comment by GoFroggyRun** [comment]
@MattHJensen 
Sure. I just updated all 8 permutations, including the trivial one which contains no reform. Please take a look [here](https://github.com/GoFroggyRun/Notebook/blob/master/TAXdata.ipynb).

**Comment by MattHJensen** [comment]
Thanks Sean. 

> ```
> reform = {
>     2015:{
>     "_II_rt1":[max(0.1 - reform_on_II,0.0)],
>     "_II_rt2":[max(0.15 - reform_on_II,0.0)],
>     "_II_rt3":[max(0.25 - reform_on_II,0.0)],
>     "_II_rt4":[max(0.28 - reform_on_II,0.0)],
>     "_II_rt5":[max(0.33 - reform_on_II,0.0)],
>     "_II_rt6":[max(0.35 - reform_on_II,0.0)],
>     "_II_rt7":[max(0.396 - reform_on_II,0.0)]}
> }
> pol
> ```

Could you switch to finding the revenue neutralizing 'percent' change rather than 'percentage point' change? 

Also, this snippet will give incorrect answers if default rates ever change in the future. Is there some way around that?

**Comment by talumbau** [comment]
@brendancol @MattHJensen @GoFroggyRun as I discussed with Brendan today, here is my attempt at place the additional text and numbers in the proper location. @MattHJensen please refine as necessary:

<img width="1066" alt="plot_with_extra_text" src="https://cloud.githubusercontent.com/assets/1891418/16247895/a8c7f382-37d1-11e6-82a8-61ce4b0e7d3a.png">

@brendancol this should be enough to get you started.

**Comment by GoFroggyRun** [comment]
@MattHJensen I just modified the [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/TAXdata.ipynb) to address your concerns, please take a look.

**Comment by talumbau** [comment]
@MattHJensen can you look at the figure above with the red text I dropped in and give feedback on the text (wording, placement, etc.)? Thanks!

**Comment by MattHJensen** [comment]
@GoFroggyRun, thanks for updating the notebook. Those look like the right calcs now. @brendancol and @talumbau, is this helpful? Would anything else be useful on the number generating front? 

---

@talumbau, as for the wording, what do you think of this? 

Have these two side by side with numbers bigger on top and text smaller on the bottom. 

XX.XX
Dollars raised in the first year. 

XX.XX
Fewer taxpayers itemizing.

Have this below those. 

These reforms could pay for higher spending, lower deficits, or a XX.XX percent tax cut for every bracket.

**Comment by talumbau** [comment]
Yes this is great. I am currently taking Sean's new functions and adding them to the calculation script. 

Text additions are great and make sense to me. @brendancol, does that all make sense to you?
