### ISSUE TITLE
ENH: the "upload" script for deploying built viz should take a version number

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/plots#9]
The plots will need to be updated as we version Tax-Calculator or other packages dependent on Tax-Calculator. Each time we release a new version, we will need to build and deploy the latest version of each viz. The deployment script should take a version number. Therefore, instead of uploading to a URL like this:

S3_BUCKET_NAME/tax_reform_explorer/index.html

it will upload to a URL like this:

S3_BUCKET_NAME/VERSION_NUMBER/tax_reform_explorer/index.html

**Comment by brendancol** [comment]
so that sounds pretty doable, except I think the path should be `S3_BUCKET_NAME/tax_reform_exploreer/VERSION_NUMBER/index.html` so there are not collision between version numbers and different plots

**Comment by brendancol** [comment]
Is my intuition correct that the `webmanifest.json` should always contain one version of each plot?

**Comment by brendancol** [comment]
https://github.com/open-source-economics/taxplots/pull/6/commits/5b8531faba5066ec995db46156cb3fc8f65d5f44
